### ISSUE TITLE
open source Crop data set CSV/JSON

### ISSUE THREAD

**Issue by eliataylor** [farmOS-legacy/farm_crop#1]
i'm trying to encourage our resident/farmers to actually use this system (properly) and it would really help to have a pre-loaded or csv/json file of standard Crops (ideally with a stock image and/or hierarchy)

**Comment by mstenta** [comment]
Hi @eliataylor - agreed that is definitely going to be a necessary feature to help people get up and running with farmOS faster.

We actually have a feature request in place for it already in the drupal.org issue queue: https://www.drupal.org/node/2379259 (I'm going to close this issue and continue the conversation over there - please join!  You'll need a drupal.org account, but that's where I do most of the planning and task management.)

I've heard this same request from a few people now, so it probably makes sense to bump up the priority.

FYI: I'm hosting a Google Hangout On Air tonight for anyone interested in discussing farmOS development, next steps, etc.  I plan to make it a monthly thing, and this will be the first one. You're welcome to join! Here is the link: https://plus.google.com/u/1/events/c2b55pcct7c2o636feurmpmmvi4
